"""Odoo v19 model/field mapping."""
from __future__ import annotations

from odoo_task_porter.versions.spec import (
    ModelMapping,
    OdooVersionSpec,
    ProjectFieldMapping,
    StageFieldMapping,
    TagFieldMapping,
    TaskFieldMapping,
    UserFieldMapping,
)


SPEC = OdooVersionSpec(
    version_name="v19",
    models=ModelMapping(
        project="project.project",
        task="project.task",
        tag="project.tags",
        stage="project.task.type",
        user="res.users",
    ),
    task=TaskFieldMapping(
        estimation_candidates=("planned_hours", "allocated_hours"),
        owner_candidates=("user_id", "user_ids"),
        field_aliases={
            "id": ("id",),
            "name": ("name",),
            "display_name": ("display_name",),
            "active": ("active",),
            "description": ("description",),
            "project": ("project_id",),
            "stage": ("stage_id",),
            "state": ("state",),
            "kanban_state": ("kanban_state",),
            "priority": ("priority",),
            "tags": ("tag_ids",),
            "owner": ("user_id", "user_ids"),
            "partner": ("partner_id",),
            "company": ("company_id",),
            "parent": ("parent_id",),
            "children": ("child_ids",),
            "dependencies": ("blocked_by", "depends_on_ids"),
            "deadline": ("date_deadline",),
            "assign_date": ("date_assigning",),
            "last_stage_update": ("date_last_stage_update",),
            "date_start": ("date_start",),
            "date_end": ("date_end",),
            "create_date": ("create_date",),
            "write_date": ("write_date",),
            "create_uid": ("create_uid",),
            "write_uid": ("write_uid",),
            "sequence": ("sequence",),
            "import_key": ("x_import_key",),
            "planned_hours": ("planned_hours", "allocated_hours"),
            "effective_hours": ("effective_hours",),
            "remaining_hours": ("remaining_hours",),
            "sale_line": ("sale_line_id",),
            "email_from": ("email_from",),
            "message_ids": ("message_ids",),
            "activity_ids": ("activity_ids",),
            "personal_stage_type": ("personal_stage_type_id",),
            "rating_last_value": ("rating_last_value",),
        },
    ),
    project=ProjectFieldMapping(
        field_aliases={
            "id": ("id",),
            "name": ("name",),
            "active": ("active",),
            "company": ("company_id",),
            "partner": ("partner_id",),
            "privacy_visibility": ("privacy_visibility",),
            "create_uid": ("create_uid",),
            "create_date": ("create_date",),
            "write_uid": ("write_uid",),
            "write_date": ("write_date",),
        },
    ),
    tag=TagFieldMapping(
        field_aliases={
            "id": ("id",),
            "name": ("name",),
            "color": ("color",),
            "create_uid": ("create_uid",),
            "create_date": ("create_date",),
            "write_uid": ("write_uid",),
            "write_date": ("write_date",),
        },
    ),
    stage=StageFieldMapping(
        field_aliases={
            "id": ("id",),
            "name": ("name",),
            "sequence": ("sequence",),
            "fold": ("fold",),
            "projects_relation": ("project_ids",),
            "create_uid": ("create_uid",),
            "create_date": ("create_date",),
            "write_uid": ("write_uid",),
            "write_date": ("write_date",),
        },
    ),
    user=UserFieldMapping(
        field_aliases={
            "id": ("id",),
            "login": ("login",),
            "name": ("name",),
            "active": ("active",),
            "partner": ("partner_id",),
            "company": ("company_id",),
            "create_uid": ("create_uid",),
            "create_date": ("create_date",),
            "write_uid": ("write_uid",),
            "write_date": ("write_date",),
        },
    ),
)
